// Code generated by goctl. DO NOT EDIT.
package types

type UserRegistoryReq struct {
	Name     string `json:"name"`
	Phone    string `json:"phone"`
	Passwd   string `json:"password"`
	Birthday string `json:"birthday"`
}

type UserRegistoryResp struct {
	Uid string `json:"uid"`
}

type UserLoginReq struct {
	Phone  string `json:"phone"`
	Passwd string `json:"password"`
}

type UserLoginResp struct {
	Uid string `json:"uid"`
}
