// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/goods.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryGoodsListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category    string `protobuf:"bytes,1,opt,name=Category,proto3" json:"Category,omitempty"`
	GoodsName   string `protobuf:"bytes,2,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	LastGoodsId int64  `protobuf:"varint,3,opt,name=LastGoodsId,proto3" json:"LastGoodsId,omitempty"`
	Size        int32  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *QueryGoodsListReq) Reset() {
	*x = QueryGoodsListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsListReq) ProtoMessage() {}

func (x *QueryGoodsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsListReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsListReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGoodsListReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QueryGoodsListReq) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *QueryGoodsListReq) GetLastGoodsId() int64 {
	if x != nil {
		return x.LastGoodsId
	}
	return 0
}

func (x *QueryGoodsListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QueryGoodsDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *QueryGoodsDetailReq) Reset() {
	*x = QueryGoodsDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsDetailReq) ProtoMessage() {}

func (x *QueryGoodsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsDetailReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsDetailReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{1}
}

func (x *QueryGoodsDetailReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type QueryGoodsAttrsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *QueryGoodsAttrsReq) Reset() {
	*x = QueryGoodsAttrsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsAttrsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsAttrsReq) ProtoMessage() {}

func (x *QueryGoodsAttrsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsAttrsReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsAttrsReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{2}
}

func (x *QueryGoodsAttrsReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type QueryGoodsSpecsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *QueryGoodsSpecsReq) Reset() {
	*x = QueryGoodsSpecsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsSpecsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsSpecsReq) ProtoMessage() {}

func (x *QueryGoodsSpecsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsSpecsReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsSpecsReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{3}
}

func (x *QueryGoodsSpecsReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type QueryGoodsSpecBySpecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64    `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Specs   []string `protobuf:"bytes,2,rep,name=Specs,proto3" json:"Specs,omitempty"`
}

func (x *QueryGoodsSpecBySpecReq) Reset() {
	*x = QueryGoodsSpecBySpecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsSpecBySpecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsSpecBySpecReq) ProtoMessage() {}

func (x *QueryGoodsSpecBySpecReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsSpecBySpecReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsSpecBySpecReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{4}
}

func (x *QueryGoodsSpecBySpecReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *QueryGoodsSpecBySpecReq) GetSpecs() []string {
	if x != nil {
		return x.Specs
	}
	return nil
}

type QueryGoodsSpecByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSpecId int64 `protobuf:"varint,1,opt,name=GoodsSpecId,proto3" json:"GoodsSpecId,omitempty"`
}

func (x *QueryGoodsSpecByIdReq) Reset() {
	*x = QueryGoodsSpecByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGoodsSpecByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGoodsSpecByIdReq) ProtoMessage() {}

func (x *QueryGoodsSpecByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGoodsSpecByIdReq.ProtoReflect.Descriptor instead.
func (*QueryGoodsSpecByIdReq) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{5}
}

func (x *QueryGoodsSpecByIdReq) GetGoodsSpecId() int64 {
	if x != nil {
		return x.GoodsSpecId
	}
	return 0
}

type GoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsList []*GoodsVO `protobuf:"bytes,1,rep,name=goodsList,proto3" json:"goodsList,omitempty"`
}

func (x *GoodsResp) Reset() {
	*x = GoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsResp) ProtoMessage() {}

func (x *GoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsResp.ProtoReflect.Descriptor instead.
func (*GoodsResp) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsResp) GetGoodsList() []*GoodsVO {
	if x != nil {
		return x.GoodsList
	}
	return nil
}

type GoodsVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId   int64  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	GoodsName string `protobuf:"bytes,2,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Company   string `protobuf:"bytes,4,opt,name=Company,proto3" json:"Company,omitempty"`
	Category  string `protobuf:"bytes,5,opt,name=Category,proto3" json:"Category,omitempty"`
	Logo      string `protobuf:"bytes,6,opt,name=Logo,proto3" json:"Logo,omitempty"`
	Content   string `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	SalePrice int32  `protobuf:"varint,8,opt,name=SalePrice,proto3" json:"SalePrice,omitempty"`
	MinPrice  int32  `protobuf:"varint,9,opt,name=MinPrice,proto3" json:"MinPrice,omitempty"`
	MaxPrice  int32  `protobuf:"varint,10,opt,name=MaxPrice,proto3" json:"MaxPrice,omitempty"`
	Stock     int32  `protobuf:"varint,11,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Sale      int32  `protobuf:"varint,12,opt,name=Sale,proto3" json:"Sale,omitempty"`
	IsAttr    int32  `protobuf:"varint,13,opt,name=IsAttr,proto3" json:"IsAttr,omitempty"`
	Status    int32  `protobuf:"varint,14,opt,name=Status,proto3" json:"Status,omitempty"`
	Deleted   int32  `protobuf:"varint,15,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	CreateAt  int64  `protobuf:"varint,16,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt  int64  `protobuf:"varint,17,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
}

func (x *GoodsVO) Reset() {
	*x = GoodsVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsVO) ProtoMessage() {}

func (x *GoodsVO) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsVO.ProtoReflect.Descriptor instead.
func (*GoodsVO) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{7}
}

func (x *GoodsVO) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsVO) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodsVO) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsVO) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *GoodsVO) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GoodsVO) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *GoodsVO) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GoodsVO) GetSalePrice() int32 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *GoodsVO) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GoodsVO) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GoodsVO) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsVO) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsVO) GetIsAttr() int32 {
	if x != nil {
		return x.IsAttr
	}
	return 0
}

func (x *GoodsVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GoodsVO) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *GoodsVO) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GoodsVO) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type GoodsDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods      *GoodsVO        `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"`
	GoodsAttrs []*GoodsAttrsVO `protobuf:"bytes,2,rep,name=goodsAttrs,proto3" json:"goodsAttrs,omitempty"`
}

func (x *GoodsDetailResp) Reset() {
	*x = GoodsDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResp) ProtoMessage() {}

func (x *GoodsDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResp.ProtoReflect.Descriptor instead.
func (*GoodsDetailResp) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{8}
}

func (x *GoodsDetailResp) GetGoods() *GoodsVO {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *GoodsDetailResp) GetGoodsAttrs() []*GoodsAttrsVO {
	if x != nil {
		return x.GoodsAttrs
	}
	return nil
}

type GoodsAttrsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsAttrs []*GoodsAttrsVO `protobuf:"bytes,1,rep,name=goodsAttrs,proto3" json:"goodsAttrs,omitempty"`
}

func (x *GoodsAttrsResp) Reset() {
	*x = GoodsAttrsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsAttrsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsAttrsResp) ProtoMessage() {}

func (x *GoodsAttrsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsAttrsResp.ProtoReflect.Descriptor instead.
func (*GoodsAttrsResp) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsAttrsResp) GetGoodsAttrs() []*GoodsAttrsVO {
	if x != nil {
		return x.GoodsAttrs
	}
	return nil
}

type GoodsAttrsVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsAttrId int64  `protobuf:"varint,1,opt,name=GoodsAttrId,proto3" json:"GoodsAttrId,omitempty"`
	GoodsId     int64  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	AttrName    string `protobuf:"bytes,3,opt,name=AttrName,proto3" json:"AttrName,omitempty"`
	AttrVals    string `protobuf:"bytes,4,opt,name=AttrVals,proto3" json:"AttrVals,omitempty"`
	Deleted     int32  `protobuf:"varint,5,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	CreateAt    int64  `protobuf:"varint,6,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt    int64  `protobuf:"varint,7,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
}

func (x *GoodsAttrsVO) Reset() {
	*x = GoodsAttrsVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsAttrsVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsAttrsVO) ProtoMessage() {}

func (x *GoodsAttrsVO) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsAttrsVO.ProtoReflect.Descriptor instead.
func (*GoodsAttrsVO) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsAttrsVO) GetGoodsAttrId() int64 {
	if x != nil {
		return x.GoodsAttrId
	}
	return 0
}

func (x *GoodsAttrsVO) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsAttrsVO) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *GoodsAttrsVO) GetAttrVals() string {
	if x != nil {
		return x.AttrVals
	}
	return ""
}

func (x *GoodsAttrsVO) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *GoodsAttrsVO) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GoodsAttrsVO) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type GoodsSpecVO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSpecId int64  `protobuf:"varint,1,opt,name=GoodsSpecId,proto3" json:"GoodsSpecId,omitempty"`
	GoodsId     int64  `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Spec        string `protobuf:"bytes,3,opt,name=Spec,proto3" json:"Spec,omitempty"`
	SalePrice   int32  `protobuf:"varint,4,opt,name=SalePrice,proto3" json:"SalePrice,omitempty"`
	Stock       int32  `protobuf:"varint,5,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Sale        int32  `protobuf:"varint,6,opt,name=Sale,proto3" json:"Sale,omitempty"`
	Preview     string `protobuf:"bytes,7,opt,name=Preview,proto3" json:"Preview,omitempty"`
	Deleted     int32  `protobuf:"varint,8,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	CreateAt    int64  `protobuf:"varint,9,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt    int64  `protobuf:"varint,10,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
}

func (x *GoodsSpecVO) Reset() {
	*x = GoodsSpecVO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsSpecVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsSpecVO) ProtoMessage() {}

func (x *GoodsSpecVO) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsSpecVO.ProtoReflect.Descriptor instead.
func (*GoodsSpecVO) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{11}
}

func (x *GoodsSpecVO) GetGoodsSpecId() int64 {
	if x != nil {
		return x.GoodsSpecId
	}
	return 0
}

func (x *GoodsSpecVO) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsSpecVO) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *GoodsSpecVO) GetSalePrice() int32 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *GoodsSpecVO) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsSpecVO) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsSpecVO) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *GoodsSpecVO) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *GoodsSpecVO) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GoodsSpecVO) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type GoodsSpecsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsSpecs []*GoodsSpecVO `protobuf:"bytes,1,rep,name=goodsSpecs,proto3" json:"goodsSpecs,omitempty"`
}

func (x *GoodsSpecsResp) Reset() {
	*x = GoodsSpecsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_goods_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsSpecsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsSpecsResp) ProtoMessage() {}

func (x *GoodsSpecsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goods_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsSpecsResp.ProtoReflect.Descriptor instead.
func (*GoodsSpecsResp) Descriptor() ([]byte, []int) {
	return file_pb_goods_proto_rawDescGZIP(), []int{12}
}

func (x *GoodsSpecsResp) GetGoodsSpecs() []*GoodsSpecVO {
	if x != nil {
		return x.GoodsSpecs
	}
	return nil
}

var File_pb_goods_proto protoreflect.FileDescriptor

var file_pb_goods_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x83, 0x01, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x17, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x42, 0x79, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x22, 0x39, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x49,
	0x64, 0x22, 0x36, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29,
	0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x56, 0x4f, 0x52, 0x09,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xbd, 0x03, 0x0a, 0x07, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x56, 0x4f, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x6f, 0x67,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x61, 0x6c, 0x65, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x61, 0x6c, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x69, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x61, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x41, 0x74, 0x74,
	0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x49, 0x73, 0x41, 0x74, 0x74, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x66, 0x0a, 0x0f, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x05,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x56, 0x4f, 0x52, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x12,
	0x30, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74,
	0x74, 0x72, 0x73, 0x56, 0x4f, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72,
	0x73, 0x22, 0x42, 0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x56, 0x4f, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x41, 0x74, 0x74, 0x72, 0x73, 0x22, 0xd4, 0x01, 0x0a, 0x0c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x56, 0x4f, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41,
	0x74, 0x74, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x74, 0x74, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x91, 0x02, 0x0a,
	0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x56, 0x4f, 0x12, 0x20, 0x0a, 0x0b,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x70, 0x65, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x61, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x53, 0x61, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x53, 0x61, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x18,
	0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74,
	0x22, 0x41, 0x0a, 0x0e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x70, 0x65, 0x63, 0x56, 0x4f, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70,
	0x65, 0x63, 0x73, 0x32, 0x86, 0x03, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x74, 0x74, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x53, 0x70, 0x65, 0x63, 0x56, 0x4f, 0x12, 0x3d, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x42, 0x79, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1b,
	0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70,
	0x65, 0x63, 0x42, 0x79, 0x53, 0x70, 0x65, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x70, 0x65, 0x63, 0x56, 0x4f, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_goods_proto_rawDescOnce sync.Once
	file_pb_goods_proto_rawDescData = file_pb_goods_proto_rawDesc
)

func file_pb_goods_proto_rawDescGZIP() []byte {
	file_pb_goods_proto_rawDescOnce.Do(func() {
		file_pb_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_goods_proto_rawDescData)
	})
	return file_pb_goods_proto_rawDescData
}

var file_pb_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_goods_proto_goTypes = []interface{}{
	(*QueryGoodsListReq)(nil),       // 0: pb.QueryGoodsListReq
	(*QueryGoodsDetailReq)(nil),     // 1: pb.QueryGoodsDetailReq
	(*QueryGoodsAttrsReq)(nil),      // 2: pb.QueryGoodsAttrsReq
	(*QueryGoodsSpecsReq)(nil),      // 3: pb.QueryGoodsSpecsReq
	(*QueryGoodsSpecBySpecReq)(nil), // 4: pb.QueryGoodsSpecBySpecReq
	(*QueryGoodsSpecByIdReq)(nil),   // 5: pb.QueryGoodsSpecByIdReq
	(*GoodsResp)(nil),               // 6: pb.GoodsResp
	(*GoodsVO)(nil),                 // 7: pb.GoodsVO
	(*GoodsDetailResp)(nil),         // 8: pb.GoodsDetailResp
	(*GoodsAttrsResp)(nil),          // 9: pb.GoodsAttrsResp
	(*GoodsAttrsVO)(nil),            // 10: pb.GoodsAttrsVO
	(*GoodsSpecVO)(nil),             // 11: pb.GoodsSpecVO
	(*GoodsSpecsResp)(nil),          // 12: pb.GoodsSpecsResp
}
var file_pb_goods_proto_depIdxs = []int32{
	7,  // 0: pb.GoodsResp.goodsList:type_name -> pb.GoodsVO
	7,  // 1: pb.GoodsDetailResp.goods:type_name -> pb.GoodsVO
	10, // 2: pb.GoodsDetailResp.goodsAttrs:type_name -> pb.GoodsAttrsVO
	10, // 3: pb.GoodsAttrsResp.goodsAttrs:type_name -> pb.GoodsAttrsVO
	11, // 4: pb.GoodsSpecsResp.goodsSpecs:type_name -> pb.GoodsSpecVO
	0,  // 5: pb.user.QueryGoodsList:input_type -> pb.QueryGoodsListReq
	2,  // 6: pb.user.QueryGoodsAttrs:input_type -> pb.QueryGoodsAttrsReq
	1,  // 7: pb.user.QueryGoodsDetail:input_type -> pb.QueryGoodsDetailReq
	5,  // 8: pb.user.QueryGoodsSpecById:input_type -> pb.QueryGoodsSpecByIdReq
	3,  // 9: pb.user.QueryGoodsSpecs:input_type -> pb.QueryGoodsSpecsReq
	4,  // 10: pb.user.QueryGoodsSpecBySpec:input_type -> pb.QueryGoodsSpecBySpecReq
	6,  // 11: pb.user.QueryGoodsList:output_type -> pb.GoodsResp
	9,  // 12: pb.user.QueryGoodsAttrs:output_type -> pb.GoodsAttrsResp
	8,  // 13: pb.user.QueryGoodsDetail:output_type -> pb.GoodsDetailResp
	11, // 14: pb.user.QueryGoodsSpecById:output_type -> pb.GoodsSpecVO
	12, // 15: pb.user.QueryGoodsSpecs:output_type -> pb.GoodsSpecsResp
	11, // 16: pb.user.QueryGoodsSpecBySpec:output_type -> pb.GoodsSpecVO
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pb_goods_proto_init() }
func file_pb_goods_proto_init() {
	if File_pb_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsAttrsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsSpecsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsSpecBySpecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGoodsSpecByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsAttrsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsAttrsVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsSpecVO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_goods_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsSpecsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_goods_proto_goTypes,
		DependencyIndexes: file_pb_goods_proto_depIdxs,
		MessageInfos:      file_pb_goods_proto_msgTypes,
	}.Build()
	File_pb_goods_proto = out.File
	file_pb_goods_proto_rawDesc = nil
	file_pb_goods_proto_goTypes = nil
	file_pb_goods_proto_depIdxs = nil
}
