// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	User interface {
		UserSave(ctx context.Context, in *UserInfoObj, opts ...grpc.CallOption) (*CommonResp, error)
		UserIdQuery(ctx context.Context, in *IdQueryReq, opts ...grpc.CallOption) (*UserInfoObj, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) UserSave(ctx context.Context, in *UserInfoObj, opts ...grpc.CallOption) (*CommonResp, error) {
	client := NewUserClient(m.cli.Conn())
	return client.UserSave(ctx, in, opts...)
}

func (m *defaultUser) UserIdQuery(ctx context.Context, in *IdQueryReq, opts ...grpc.CallOption) (*UserInfoObj, error) {
	client := NewUserClient(m.cli.Conn())
	return client.UserIdQuery(ctx, in, opts...)
}
