// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"github.com/zhovdawei/gozero-micro-service/user/rpc/internal/logic"
	"github.com/zhovdawei/gozero-micro-service/user/rpc/internal/svc"
	"github.com/zhovdawei/gozero-micro-service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserSave(ctx context.Context, in *user.UserInfoObj) (*user.CommonResp, error) {
	l := logic.NewUserSaveLogic(ctx, s.svcCtx)
	return l.UserSave(in)
}

func (s *UserServer) UserIdQuery(ctx context.Context, in *user.IdQueryReq) (*user.UserInfoObj, error) {
	l := logic.NewUserIdQueryLogic(ctx, s.svcCtx)
	return l.UserIdQuery(in)
}
