// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/zhovdawei/gozero-micro-service/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/query",
				Handler: userQueryByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userPost/query",
				Handler: userPostQueryByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/userPost/queryList",
				Handler: userPostQueryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: userLoginByPhoneHandler(serverCtx),
			},
		},
	)
}
