// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	mt "github.com/zhovdawei/gozero-micro-service/goods/cmd/api/internal/handler/mt"
	pc "github.com/zhovdawei/gozero-micro-service/goods/cmd/api/internal/handler/pc"
	"github.com/zhovdawei/gozero-micro-service/goods/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/queryList",
					Handler: pc.QueryGoodsListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/goods/pc/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/queryList",
				Handler: mt.QueryGoodsListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/goods/mt/v1"),
	)
}
